server:
  port: 8089
  error:
    include-message: always
spring:
  application:
    name: customer-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/foodies


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true
    registerWithEureka: true