server:
  port: 8082
spring:
  application:
    name: user-authentication-service
  datasource:
    url: jdbc:mysql://localhost:3306/foodieusers
    username: root
    password: root
    driver: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true
    registerWithEureka: true