server:
  port: 8087
spring:
  application:
    name: restaurant-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/foodies


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true
    registerWithEureka: true